### PR TITLE
modify hover color for schedule list and fix background

### PR DESCRIPTION
**Pull request by nasyaoris**

### CODE REVIEW

**Comment by fairuzi10** [comment]
Could you please revert your local change on `backend/README.md`?

**Comment by nasyaoris** [comment]
> Could you please revert your local change on `backend/README.md`?

reverted

**Comment by fairuzi10** [comment]
> > Could you please revert your local change on `backend/README.md`?
> 
> reverted

Ups, sorry forgot to mention `start_db.sh` as well.

**Comment by nasyaoris** [comment]
> > > Could you please revert your local change on `backend/README.md`?
> > 
> > 
> > reverted
> 
> Ups, sorry forgot to mention `start_db.sh` as well.

reverted, thank you

**Comment by fairuzi10** [comment]
Nice, LGTM

**Pull request merged**
